#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/kraoshin/.vscode-server/bin/2fc07b811f760549dab9be9d2bedd06c51dfcb9a/node" "/home/kraoshin/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"