#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/home/kraoshin/.vscode-server/bin/6609ac3d66f4eade5cf376d1cb76f13985724bcb/node" "/home/kraoshin/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"